name: PowerShell Lint (PSScriptAnalyzer)

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ main ]

jobs:
  psscriptanalyzer:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
        with:
          powershell-version: '7.4'

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -AllowClobber

      - name: Run Invoke-ScriptAnalyzer
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if (Test-Path .\.psscriptanalyzer.psd1) {
              Invoke-ScriptAnalyzer -Path . -Recurse -SettingsPath .\.psscriptanalyzer.psd1 | Tee-Object -Variable findings
          }
          else {
              Invoke-ScriptAnalyzer -Path . -Recurse | Tee-Object -Variable findings
          }

          if ($findings.Count -gt 0) {
              Write-Host "PSScriptAnalyzer found $($findings.Count) issue(s):" -ForegroundColor Yellow
              $findings | ForEach-Object { Write-Host "[$($_.RuleName)] $($_.FilePath):$($_.Line) - $($_.Message)" }
              throw 'PSScriptAnalyzer issues detected. Fix or suppress them before merging.'
          }
